### ISSUE TITLE
Second catch in a function gives warning 'e' is already defined

### ISSUE THREAD

**Issue by ghost** [douglascrockford/JSLint#116]
Mr. Crockford,

My understanding is that the parameter to the catch clause is like a function parameter and the catch clause has block scope.  So, the parameter to the catch clause is only visible within the catch block.

I have two try/catch pairs in a function and named both parameters to catch 'e', like so:  catch (e) {}.

Lint is reporting for the second 'e' that "'e' is already defined."  I believe this is incorrect.

Thanks,

TR

**Comment by jacksonrayhamilton** [comment]
This warning is still present in JSLint 2015-12-18. But since JSLint seems to no longer support ES3, and thus (I'm supposing) it also no longer supports [the browsers where this was an issue](https://bocoup.com/weblog/the-catch-with-try-catch), shouldn't this warning be removed?

**Comment by douglascrockford** [comment]
No.
