### ISSUE TITLE
Missing nomen option to disable _<variable> named variabels.

### ISSUE THREAD

**Issue by pietervandereems** [douglascrockford/JSLint#174]
There used to be a nomen option to disable the warnings for _<name> variables.
I program a lot of code using Couchdb as the document store. In couchdb some default fields in documents start with _, like: _id and _rev. When manipulating documents the _id and _rev are very important to set correctly so there is a lot of code like: doc._id = 'documentId1';. Without the nomen option I get a lot of errors about _id and _rev, it makes finding the "real" errors more difficult.

I'm open to suggestions on how to avoid doc._id and doc._rev when handling Couchdb documents in Javascript.

**Comment by douglascrockford** [comment]
/*property _id, _rev */
