### ISSUE TITLE
ES6 modules are always in strict mode yet JSLint still require "use strict"; in functions in the module

### ISSUE THREAD

**Issue by LJNielsenDk** [douglascrockford/JSLint#179]
[Relevant specification section](http://www.ecma-international.org/ecma-262/6.0/#sec-strict-mode-code)

I guess it isn't forbidden to do so, but does it really add anything to require/encourage it when it's redundant?

**Comment by douglascrockford** [comment]
Thanks. What does the spec consider to be Module Code? Is it the expression given to 'export', or is it the whole code unit that contains 'export'?

**Comment by LJNielsenDk** [comment]
[From the spec](http://www.ecma-international.org/ecma-262/6.0/#sec-types-of-source-code):
> Module code is source text that is code that is provided as a ModuleBody. It is the code that is directly evaluated when a module is initialized. The module code of a particular module does not include any source text that is parsed as part of a nested FunctionDeclaration, FunctionExpression, GeneratorDeclaration, GeneratorExpression, MethodDefinition, ArrowFunction, ClassDeclaration, or ClassExpression.

**Comment by douglascrockford** [comment]
Can you please give an example?

**Comment by ajhyndman** [comment]
Babel and Traceur interpret this spec as the entire code unit that contains export.

http://stackoverflow.com/questions/34366875/why-does-transform-es2015-modules-commonjs-add-use-strict-in-babel-6

https://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015%2Cstage-2&experimental=true&loose=false&spec=true&code=const%20x%20%3D%201%3B%0A%0Aconst%20myFunction%20%3D%20function%20()%20%7B%0A%20%20const%20y%20%3D%202%3B%0A%7D%3B%0A%0Aexport%20default%20myFunction%3B
