### ISSUE TITLE
Not all types of exports in ES6 modules should end with a semicolon

### ISSUE THREAD

**Issue by LJNielsenDk** [douglascrockford/JSLint#180]
[Relevant spec section](http://www.ecma-international.org/ecma-262/6.0/#sec-exports)

**Comment by douglascrockford** [comment]
Can you be more specific?

**Comment by LJNielsenDk** [comment]
[Section "16.4.4 All exporting styles" of Exploring ES6 lists the different ways to export](http://exploringjs.com/es6/ch_modules.html)

**Comment by douglascrockford** [comment]
Can you please give an example?

**Comment by Ganbin** [comment]
If I can give my 2 cents, I am using Atom editor with linter and linter-jslint packages.

For example, I get this error when I do an import : 

`Expected an identifier instead saw '{'`

When my import is a correct ES6 import : 

`import {moduleName} from 'moduleFile'`

Is it a jslint feature missing or a problem of configuration?

I have the `es6` parameter set to `true`.
