### ISSUE TITLE
Falsely reported redefinition

### ISSUE THREAD

**Issue by feklee** [douglascrockford/JSLint#186]
Example code:

    "use strict";

    var x = null;

    console.log(x);

    module.exports = {
        set x(newX) {
            x = newX;
        }
    };

Bogus error messages by [JSLint][1] edition 2016-06-09 with options *Node.js* and *ES6*:

  * Redefinition of 'x' from line 2.

        set x(newX) {

  * Bad assignment to 'x'.

        x = newX;

[1]: http://jslint.com/

**Comment by douglascrockford** [comment]
JSLint is warning you that you have too many things called x. That can lead to confusion, which can lead to bugs. Think of another name.
