### ISSUE TITLE
Inconsistent warning about redefinition

### ISSUE THREAD

**Issue by feklee** [douglascrockford/JSLint#187]
The following code passes [JSLint][1] edition 2016-06-09 with options *Node.js* and *ES6:*

    "use strict";

    var x = null;

    console.log(x);

    module.exports = Object.create(null, {
        x: {
            set: function (newX) {
                x = newX;
            }
        }
    });

This one doesn’t:

    "use strict";

    var x = null;

    console.log(x);

    module.exports = {
        set x(newX) {
            x = newX;
        }
    };

In both cases, a setter `x` is created, that sets – you guessed it – a variable called `x`. To make the second code pass, I would need to change the internal variable to something like `xInternal`, i.e. Hungarian notation. From my experience that makes code harder to read.

[1]: http://jslint.com/

**Comment by douglascrockford** [comment]
In the first case, the second x is a property. That is a separate namespace.

I am not recommending that you use Hungarian notation. You might want to consider not using setters.

**Comment by feklee** [comment]
It’s a property in both cases, no? I don’t see a difference.

**Comment by douglascrockford** [comment]
In the second case it is also the name of the setter function.

**Comment by feklee** [comment]
Thanks for pointing that out! Just visualized it using the Chrome developer tools’ console:

![Screenshot of Chrome developer tools’ console](https://cloud.githubusercontent.com/assets/14994/16035056/6d70a03e-3215-11e6-8a52-caf6f4baa208.png)

All instances of `x` have different scopes. Therefore, JSLint’s error message about “Redefinition” is wrong!

**Comment by douglascrockford** [comment]
JSLint has stricter scope rules to help humans avoid confusion.

**Comment by feklee** [comment]
The error message is confusing me. I suggest you give it a different name.
