### ISSUE TITLE
Spaces before casts

### ISSUE THREAD

**Issue by vandenoever** [douglascrockford/JSLint#188]
Closure Compiler requires type annotations in comments.
JSLint sees the type annotation comment as undesired spacing.

```javascript
    if (node.nodeType === 1) {
        handleNode(/**@type{!Element}*/(node));
    }
```
```
Unexpected space between '(' and '('.
```

**Comment by douglascrockford** [comment]
Thanks. Please try it now.

That Closure crap is pretty nasty looking.

**Comment by vandenoever** [comment]
Fix confirmed. Thanks.
I use Closure Compiler as an additional linting step.  Yes, the type annotations are ugly.
