### ISSUE TITLE
Expected an identifier instead saw '{'

### ISSUE THREAD

**Issue by Ganbin** [douglascrockford/JSLint#194]
If I can give my 2 cents, I am using Atom editor with linter and linter-jslint packages.

For example, I get this error when I do an import :

Expected an identifier instead saw '{'

When my import is a correct ES6 import :

import {moduleName} from 'moduleFile'

Is it a jslint feature missing or a problem of configuration?

I have the es6 parameter set to true.

**Comment by tensor5** [comment]
@Ganbin, linter-jslint is based on an old version of JSLint. May I recommend you my [linter-jslinter](https://atom.io/packages/linter-jslinter) plugin?

**Comment by Ganbin** [comment]
Ok thanks @tensor5 your package is good and solve my issue.

Another question I have is why jslint always expect a default exported property?
