### ISSUE TITLE
jsLint complaint about 'for' statement

### ISSUE THREAD

**Issue by int21ve** [douglascrockford/JSLint#199]
Hi, first at all, thanks for this great tool called 'jslint' 
I have this "problem" or issues when I parse my code with jslint.

/*jslint multivar:true */
function looping2(n) {
    "use strict";
    var a = 0, b = 1, f = 1;
    for(var i = 2; i <= n;  i = i + 1) {
        f = a + b;
        a = b;
        b = f;
    }
    return f;
}

JSLint gave this warning:

Unexpected 'for'.
Unexpected 'var'.

Then I changed my code to this:

function looping(n) {
    "use strict";
    var a = 0, b = 1, f = 1, i;
    for (i = 2; i <= n; i = i + 1) {
        f = a + b;
        a = b;
        b = f;
    }
    return f;
}

...and still complaint about the 'for' statement.

What's your thoughts about for statement? 
I think you saw 'for' only to be used with arrays and not for simple looping.

Thank you, and please don't complaint abot my english grammar, I'm foreing.

**Comment by douglascrockford** [comment]
Read the instructions or use the 'for' option.

**Comment by int21ve** [comment]
Instructions: 

> JSLint does not recommend use of the for statement. Use array methods like forEach instead.

How can I use forEach  in this code? When is clearly a simple "loop"  that said: "go from zero to a max number(N).
Please I don't ge it.

**Comment by douglascrockford** [comment]
...or use the 'for' option.

**Comment by int21ve** [comment]
I ended up using a while loop statement.
Anyway, thanks about the tip using the 'for' option to avoid the warning.
I'd prefer having an explanation about the JSLint rule with 'for' statements and how to solve rather than using the silent option 'for;

**_Best regards_**
