### ISSUE TITLE
Missing ECMAScript 2016 features

### ISSUE THREAD

**Issue by friendlyanon** [douglascrockford/JSLint#200]
So I just tossed in one of my userscripts into JSLint for fun and I came to notice that it cannot recognize arrow functions and template literals, and it completely stops processing the input if the two are combined.

JSLint also complains when you [pass in an argument to a function with a template literal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Tagged_template_literals), but I guess that's related to the above complaints.

**Comment by douglascrockford** [comment]
Those constructions are unnecessarily complicated and error-prone. I recommend that you simplify your code.
