### ISSUE TITLE
Conflicting warnings regarding space character within a regular expression

### ISSUE THREAD

**Issue by onetwothreefall** [douglascrockford/JSLint#204]
I use a small regular expression `/[\ \t]+$/gm` to remove trailing spaces/tabs from each line of a multi-line string, and it was previously accepted without issue from JSLint. (I can test and see which version this behaviour changed, if you wish.)

With the current version (2017-01-20), however, the line

    let a = /[\ \t]+$/gm;

will trigger the warning `Unexpected '\' before ' '.`

Removing the '\\' escape character before the space, as recommended

    let b = /[ \t]+$/gm;

will instead trigger the warning `Expected '\' before ' '.`

Which of these warnings is correct?

**Comment by douglascrockford** [comment]
Putting a space in a regexp is asking for trouble. Instead us \u0020 or \s, or even better, use the trim method.

**Comment by onetwothreefall** [comment]
Sorry for not being too clear, but the issue I was trying to bring up wasn't related to the use of spaces, but instead the conflicting/incorrect warnings. If \s or \u0020 is recommended, the warning should try to indicate this, rather than suggesting to add/remove the '\\' character.
