### ISSUE TITLE
Unexpected '['

### ISSUE THREAD

**Issue by Nimzozo** [douglascrockford/JSLint#207]
I've got the message `Unexpected '['` with this code :

```javascript
function doSomething() {
  // Do something
}
["something", "something else"].forEach(doSomething);
```

But not with this code :

```javascript
var something = "";
function doSomething() {
  // Do something
}
something = "something";
[something, "something else"].forEach(doSomething);
```

Is there something wrong with using directly an array to call a function ?

**Comment by douglascrockford** [comment]
There can be. And as you demonstrated, it is necessary.

**Comment by Nimzozo** [comment]
I think the message should appear in both cases then.
