### ISSUE TITLE
Malware? Clamav scan found infected file from your repo

### ISSUE THREAD

**Issue by rodrev** [douglascrockford/JSLint#210]
Hello,
I've just run a scan with Clamav and it marked a file from your repo as malware. Can you pls have a look and let me know if I should report this as a false positive or if there is possibly some security flaw in the code that you can find. Thank you.

This is the filename and output from clamscan:
```
~/.npm/linter/0.0.7/package/deps/JSLint/fulljslint.js
Sanesecurity.Malware.26587.JsHeur.UNOFFICIAL FOUND
```

**Comment by douglascrockford** [comment]
I have no packages on NPM.

**Comment by rodrev** [comment]
Sorry looks like it is the linter npm package that is pulling your package as a dependency.  Most likely it is a false positive anyway. But I thought it best to ask you to be safe.  Thanks again.
