### ISSUE TITLE
why Unexpected '?'.

### ISSUE THREAD

**Issue by einst3** [douglascrockford/JSLint#215]
why is s =... line giving Unexpected "?" ? if i change either ternary its works. i get it, if both terms are same then it will give unexpected, but should it?
function rootx() {
    "use strict";
    var line,i,s;
    for (line=1; line<30; line+=1) {
        for(i=1;i<29;i+=1) {
            s = (Math.floor((Math.random()*2)%2)) ? "?" : "?";
            document.write(s);
        }
        document.writeln("&lt;br&gt;");
    }
}

**Comment by douglascrockford** [comment]
Both consequences of the ternary operator are "?". JSLint thinks you are misusing the ternary operator.
