### ISSUE TITLE
why Unexpected '\' before 'x'.

### ISSUE THREAD

**Issue by einst3** [douglascrockford/JSLint#216]
why Unexpected '\\' before 'x'. ?
function trx(s) {"use strict";var rtrx=/^[\x0B\xA0]+|[\x0B\xA0]+$/g;return s.replace(rtrx,"");}

**Comment by douglascrockford** [comment]
Don't use \x. Use \u instead.

**Comment by einst3** [comment]
i have some browsers on older os that dont support es6 but support es5. unicode 3 is supported in es5 and unicode 5+ is supported in es6. is it possible to keep the \\x instead of the new \\u?

**Comment by douglascrockford** [comment]
\u is in ES5.
