### ISSUE TITLE
The export statement doesn't work as intended.

### ISSUE THREAD

**Issue by Guest93** [douglascrockford/JSLint#220]
Example code:

    function myFunction(a, b) {
        return a + b;
    }
    export myFunction;

l.3.7: Unexpected 'myFunction'.
--- export myFunction;

The reason which might be:

in stmt("export"):
  function export_id():
    the_export.expression.push(the_thing); //(l.3335)

"the_thing" is undefined for the two cases where export_id() is called

**Comment by douglascrockford** [comment]
I think you meant one of these:

    export default myFunction;
    export {myFunction};

**Comment by Guest93** [comment]
On the Help-Page you state that it's supported; and likewise says the code
Regardless of that, it is still a fact that the above mentioned function ``export_id`` only pushes ``undefined`` into ``the_export.expression``

**Comment by douglascrockford** [comment]
JSLint only allows that form for const. The function declaration is a var.
