### ISSUE TITLE
Link to "The Good Parts" is corrupt

### ISSUE THREAD

**Issue by Krinkle** [douglascrockford/JSLint#222]
The link on https://jslint.com to "The Good Parts" seems to have been corrupted by the minification used on the HTML.

In source:

https://github.com/douglascrockford/JSLint/blob/0e5065a51a7602499aa500c1db4125145f5dbeb3/jslint.html#L360-L363

```html
    <li><a
        href="http://www.amazon.com/exec/obidos/ASIN/0596517742/wrrrldwideweb"
        target="_blank"
    >Read&nbsp;<i>The Good Parts</i>.</a></li>
```

In production:

```html
<li><a href="http:target="_blank">Read&nbsp;<i>The Good Parts</i>.</a></li>
```

Which browsers seem to (somehow) expand as <http://www.jslint.com/target=>, (switching protocols, and then appending a relative path).

**Comment by douglascrockford** [comment]
Thanks.
