### ISSUE TITLE
Older version

### ISSUE THREAD

**Issue by markbernard** [douglascrockford/JSLint#225]
First let me say I love this tool and use it all the time. However, I cannot use it at work any more since where I work we are only allowed to use IE11 and the current version does not run on IE11. I couldn't find an older release to download and run locally. Is there a link to an older version that I can use?

**Comment by douglascrockford** [comment]
No. I am dedicated to eliminating IE in all of its detestable forms.

Have you considered running JSLint in node.js?

**Comment by nikoskalogridis** [comment]
@markbernard shameless plug [jslint-node](https://github.com/nikoskalogridis/jslint-node)

**Comment by markbernard** [comment]
Ok. Thanks for answering. We are not allowed to use node.js either.

**Comment by douglascrockford** [comment]
Are you allowed to use Java?

**Comment by markbernard** [comment]
Yes. We use Java.

**Comment by douglascrockford** [comment]
The latest Java can run JavaScript;.assuming that they let you use the latest.

**Comment by markbernard** [comment]
Ok. I'll see if I can get that working.

Thanks.

**Comment by kaizhu256** [comment]
hi @markbernard, i tagged several historical milestones of jslint @ https://github.com/douglascrockford/JSLint/issues/236 and https://github.com/kaizhu256/jslint/tags.  if you're looking for stable versions of jslint.js, you generally want the commit that's one-below the tagged milestone ; )

**Comment by markbernard** [comment]
Thanks very much. I understand wanting to get rid of IE, but that attitude
leaves a lot of people without good tool since large organizations are very
slow to change. I am not even allowed to install another browser.
