### ISSUE TITLE
sure would be nice if JSLint supported "export const tau = 6.2"

### ISSUE THREAD

**Issue by magicmouse** [douglascrockford/JSLint#226]
Currently JSLint complains about "export const name = val", which is a very common form.
It also is not fond of "export let varname". Both are widely published as reasonable ways to export a variable or constant, and unfortunately there is no way to turn off export errors in JSLint, so it kills all of my JSLints.

**Comment by douglascrockford** [comment]
I will consider a valid argument. Popularity is not a valid argument.

**Comment by magicmouse** [comment]
There are several reasons for supporting the one line form of export more completely:

1) adding this syntactical pattern would to assist in the graceful transition in the huge quantity of Ecmascript code that currently resides in a different dialect, namely Actionscript 3 code. By a simple find/replace operation one can replace the 'public static const' used in Actionscript, with 'export const', and thus be transformed into JS, latest dialect. If JSLint were to support export const, export let, the JS transition would be less painful.

2) Javascript with the addition of "let", and module support, and other recently added features, finally converged sufficiently with Actionscript that it is feasible for automatic translation tools (of which am building), to transform large amounts of debugged code into Javascript. 

3) to support export const myname = val, and export let myname = val, should be pretty trivial to add to the JSLint program.

**Comment by douglascrockford** [comment]
I will not dumb down JSLint to preserve bad practices from ActionScript.

**Comment by magicmouse** [comment]
You have already done so much work on my language project already, with your many valuable suggestions about the Pratt compiler, DEC64 arithmetic, and numerous other observations about what the post-javascript apocalypse will look like, i hate to cause even the slightest discomfort to you. 

Perhaps since you don't want to modify JSLint to allow export const TAU = 6.28 as valid, you could please eliminate the error count limit, because i can live with ignoring the messages, but since i hit the max error limit because of these messages, i can't use the other valuable findings of JSLint. Perhaps it could be a command line option to set the limit of errors before it quits.

But the fact remains that i don't understand your objection to recognizing valid syntax of "export const TAU = 6.28". In my case i have a very large system, with many modules, and some of them are used to store commonly used constants, like color names. I was trained by Prof. Wirth at ETH to build products in a modular nature, and in fact Modula-2 is the grand-daddy of all module systems, as it was the first language (and apparently the last) to support separately compileable modules. Modula2 came 10 years after he invented Pascal, and was designed for very robust large system program development. In Modula-2's case, there was a separate file called a Definition file that listed all the exported constants, records, types, functions of a module, and then there was an implementation file that held the executable code. Due to the syntax, all imports had to be listed at the top of each module, and therefore the compiler could quickly scan the source files to determine the cross-dependencies, and huge programs would rebuild in a few seconds, because the dependency graph could be so quickly built. Compare that to the decades old mess that is the C header file mess, which even C++ has not fixed after decades of evolution. Having used Modula-2  extensively, it did work well. However, Wirth himself found it a pain in the rear to keep the definition file up to date; it involved a lot of extra typing, and in his next language Oberon, he dropped the separate DEFINITION and IMPLEMENTATION module approach, and you marked a name as exported by appending an asterisk after the name. A much more abbreviated approach; however, you lost the ability to separately compile, which has many virtues, not the least of which is you can supply a library module with definition code, and keep the implementation secret, which would allow for a marketplace of libraries with very precise definitions. Javascript is now recapitulating the module approach, and appears to come in closer to Oberon's approach, where you have a single file and either mark a symbol as exported at the point of definition, or alternatively at the very end of the module. I am not sure why you disfavor inline export; once you start having a lot of exports, putting all the export statements at the end is duplicate typing, and to make code easier to cut/paste as you shuffle it between modules, a very common task during refactoring, having the export carried with the symbol makes a lot of sense and avoids errors.  Most large systems will have lots of modules that are just libraries of low-level functions, constants, etc.
