### ISSUE TITLE
bug - second-line following shebang is not properly linted

### ISSUE THREAD

**Issue by kaizhu256** [douglascrockford/JSLint#235]
the latest commit to master (https://github.com/douglascrockford/JSLint/commit/04f838b3986c8e0f02e56438aade342552aac93f) fails to lint the second-line, following shebang.  note that the original ignore_shebang pull-request (https://github.com/douglascrockford/JSLint/pull/234) doesn't have this bug.

-screenshot showing current-master branch failing to lint second-line after shebang. master web-demo at: https://kaizhu256.github.io/JSLint/branch.master/index.html
![image](https://user-images.githubusercontent.com/280571/45611457-b123cf00-ba89-11e8-9822-2c552c3061b0.png)

-screenshot showing original ignore_shebang pull-request (https://github.com/douglascrockford/JSLint/pull/234) not having this bug. pull-request web-demo at: https://kaizhu256.github.io/JSLint/branch.ignore_shebang/index.html
![image](https://user-images.githubusercontent.com/280571/45611526-e03a4080-ba89-11e8-8c45-5a2874bcbd9c.png)

**Comment by douglascrockford** [comment]
Thanks. Please try it now.
