### ISSUE TITLE
create gh-pages branch which tracks master branch

### ISSUE THREAD

**Issue by kaizhu256** [douglascrockford/JSLint#237]
this will allow general-public to preview and test latest master-branch
at live web-demo: https://douglascrockford.github.io/JSLint/

![screen shot 2018-09-25 at 5 14 54 pm](https://user-images.githubusercontent.com/280571/46008327-9afbbb80-c0e6-11e8-9502-1b0e596ab4f7.png)

**Comment by douglascrockford** [comment]
jslint.com
