### ISSUE TITLE
30kb json-file cause recursion error - RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by kaizhu256** [douglascrockford/JSLint#239]
i tried to jslint a 30kb json-file from http://kaizhu256.github.io/node-swgg/build..beta..travis-ci.org/app/assets.swgg.swagger.server.json

here's the two-lines that over-recurse, along with stack-trace

```diff
            } else if (char === "`") {
                if (mega_mode) {
                    warn_at("unexpected_a", line, column, "`");
                }
                next_char("`");
            } else {
+                next_char();
            }
+            return next();
        }());
    }

    function frack() {
        if (char === ".") {

RangeError: Maximum call stack size exceeded
    at next_char (jslint.js:654)
    at next (jslint.js:1179)
    at next (jslint.js:1181)
    at next (jslint.js:1181)
    at next (jslint.js:1181)
    at next (jslint.js:1181)
    at next (jslint.js:1181)
    at next (jslint.js:1181)
    at next (jslint.js:1181)
    at next (jslint.js:1181)
```

screenshot showing recursion error (http://jslint.com/). i verified this bug occurs for all es6-versions of jslint.

![screen shot 2018-09-27 at 9 06 17 am](https://user-images.githubusercontent.com/280571/46119576-d5c03980-c235-11e8-808a-45e4fd36411e.png)

screenshot showing older es5 jslint working ok (https://kaizhu256.github.io/JSLint/branch.es5_web/jslint.html)

![screen shot 2018-09-27 at 9 08 32 am](https://user-images.githubusercontent.com/280571/46119642-29cb1e00-c236-11e8-9b43-f85be00dce97.png)

**Comment by douglascrockford** [comment]
JSLint requires an ES6 compliant JavaScript engine. File a bug report against your non-standards compliant engine.

**Comment by kaizhu256** [comment]
filed v8 bug-report @ https://bugs.chromium.org/p/v8/issues/detail?id=8234

**Comment by kaizhu256** [comment]
using this temporay bug-workaround when jslinting json files:

```diff
 local.errorList = local.result.warnings.filter(function (error) {
     return (
         error
         && error.message
+        // bug-workaround - v8 tail-call issue
+        // https://bugs.chromium.org/p/v8/issues/detail?id=8234
+        && error.message !== "Maximum call stack size exceeded"
     );
 }).map(function (error) {
```

**Comment by kaizhu256** [comment]
a cli-tool for the latest master-branch would make it easier to explain how to reproduce/debug these bugs in external bug-reports
