### ISSUE TITLE
bug in jslint version 2012-02-03

### ISSUE THREAD

**Issue by arehman849** [douglascrockford/JSLint#247]
evalmachine.<anonymous>:2574
        s.string = s;
                 ^

TypeError: Cannot create property 'string' on string '(begin)'

![image](https://user-images.githubusercontent.com/40396240/52414283-e2b93780-2b09-11e9-9dc3-b14d0f23541d.png)

i assume the highlighted expression must be "x.string = s" 
i am using "jslint-2012-02-03.js" file 

the reason behind picking the older version of jslint file is due to the project compatibility this project of mine is quite a old and when it was started i integrated it with the same version of file, using the newer version is failing my builds in jenkins and reports enormous errors related to whitespaces, mixed spaces and indentation. can u kindly suggest any alternative solutions for this

**Comment by douglascrockford** [comment]
Fix your code and use the latest.

**Comment by arehman849** [comment]
I could have done that but it's a huge code base of about 30k+ files it
would be difficult task for me at this point of time since we are into
stabilizing stage. Also this issue raised since we are moving one of our
branch from ant to gulp script and gulp-jslint has this problem due to
which all my builds are failing

**Comment by arehman849** [comment]
Kindly update if i will be getting any resolution for this issue....

**Comment by douglascrockford** [comment]
Fix your code and use the latest.

**Comment by arehman849** [comment]
if at all i had an option to fix my code as easy as this minor bug in your code (quality tool as you say) i would have done that.. all it takes is just to make one single commit in your code base. i have given you the point where the problem is and yet there's lack of support. anyways thanks for your valuable suggestion

**Comment by douglascrockford** [comment]
Report a problem in the current version and I will fix it immediately, making a new current version.
