### ISSUE TITLE
Line breaking rules

### ISSUE THREAD

**Issue by bunglegrind** [douglascrockford/JSLint#249]
Hello,
I'm having problems in passing JSLint validation whenever I break a longer-than-80-chars line in multiple rows.

I don't get the underlying rules JSLint follows to allow line breaks. Neither the instructions nor the book (how javascript works) helped me.

Specifically, if I have a long string definition (possibly concatenated with variable values) and I break the line in shorter rows JSLint complains about a missing space between the last and the first characters of the row.

I prepared the following snippet to show exactly the issue: 

```
/*jslint
    browser, devel
*/

/*global
    key, value, db, another_line, long_line
*/

const long_line = "SELECT * FROM " + db.name + " WHERE " + key + " = " + value + " LIMIT 0, 30";
console.log(long_line);
```

(here JSLint complains about the row too long).

So I break the line in the following ways:

1)

```
const long_line = "SELECT * FROM " + db.name +
" WHERE " + key + " = " + value + " LIMIT 0, 30";
```

2)

```
const long_line = "SELECT * FROM " + db.name
+ " WHERE " + key + " = " + value + " LIMIT 0, 30";
```

but JSLint show me the following warning:

1)

Expected one space between '+' and ' WHERE '.
`" WHERE " + key + " = " + value + " LIMIT 0, 30";`

2)

Expected one space between 'name' and '+'.
`+ " WHERE " + key + " = " + value + " LIMIT 0, 30";`

Surprisingly, after having inspected JSLint code (in particular, function one_space() at line 4581) I found that the following  script gives no warning:

```
/*jslint
    browser, devel
*/

/*global
    db, another_line
*/



const another_line = "SELECT * FROM "
                                      + db.name;

console.log(another_line);
```
Any suggestions?

Thanks in advance

**Comment by EvgenyOrekhov** [comment]
```js
const long_line = (
    "SELECT * FROM "
    + db.name
    + " WHERE "
    + key
    + " = "
    + value
    + " LIMIT 0, 30"
);
```

Or, better yet

```js
const long_line = `
    SELECT * FROM ${db.name}
    WHERE ${key} = ${value}
    LIMIT 0, 30
`;
```

**Comment by nikoskalogridis** [comment]
Irrelevant to your question I hope that you neither:

- constructing sql queries on the browser and sending them back for execution on the backend. 
- nor using user entered values for the `key, value, db.name` attributes. 

Otherwise you are opening yourself an sql injection attack vector.

**Comment by bunglegrind** [comment]
> Otherwise you are opening yourself an sql injection attack vector.


my example was not related to actual code :P I wrote it directly in the jslint website. I set the browser flag just to insert the global directive. (btw, I was working on node)

```

> const long_line = (
>     "SELECT * FROM "
>     + db.name
>     + " WHERE "
>     + key
>     + " = "
>     + value
>     + " LIMIT 0, 30"
> );

```
Ok, using parenthesis is the point I was missing. Thanks!
