### ISSUE TITLE
async/await syntax

### ISSUE THREAD

**Issue by EvgenyOrekhov** [douglascrockford/JSLint#253]
Many popular libraries use async/await extensively, here is an example from [Ember documentation](https://guides.emberjs.com/release/testing/acceptance/#toc_asynchronous-helpers):

```js
test('should add new post', async function(assert) {
  await visit('/posts/new');
  await fillIn('input.title', 'My new post');
  await click('button.submit');
  assert.equal(this.element.querySelector('ul.posts li').textContent, 'My new post');
});
```

Though I have not been using async/await much, I think that code is straightforward, and I can understand it easily. And rewriting it using Promises would make the code cumbersome.

And since that is (as far as I know) the only way of writing acceptance tests for Ember applications, giving up using that test library is also not an option.

I would like to be able to use JSLint with code that uses async/await syntax.

**Comment by kaizhu256** [comment]
@EvgenyOrekhov, there's a pending pull-request to add it #251

in meantime, you can customize your jslint with the following patch (i've been using it for 2 weeks so far with no issues):

```diff
// Deliver the next token, skipping the comments.

    const cadet = tokens[token_nr];
+    // hack-jslint - advance token async/await to next_token by context
+    const next_cadet = tokens[token_nr] || {};
+    if (next_cadet.identifier && (
+        cadet.id === "await"
+        || (cadet.id === "async" && next_cadet.id === "function")
+    )) {
+        cadet.id = next_cadet.id;
+        token_nr += 1;
+    }
    token_nr += 1;
    if (cadet.id === "(comment)") {
        if (json_mode) {
```

working-demo of patched-jslint available @ https://kaizhu256.github.io/JSLint/branch.async_await/index.html

![image](https://user-images.githubusercontent.com/280571/63235379-bee45600-c1fe-11e9-8fdb-342e488a095c.png)

**Comment by kaizhu256** [comment]
updated patch

```diff
// Deliver the next token, skipping the comments.

    const cadet = tokens[token_nr];
    token_nr += 1;
+    // hack-jslint - advance token async/await to next_token by context
+    const next_cadet = tokens[token_nr] || {};
+    if (next_cadet.identifier && (
+        cadet.id === "await"
+        || (cadet.id === "async" && next_cadet.id === "function")
+    )) {
+        cadet.id = next_cadet.id;
+        token_nr += 1;
+    }
    if (cadet.id === "(comment)") {
        if (json_mode) {
```

**Comment by EvgenyOrekhov** [comment]
I don't care anymore.

**Comment by kaizhu256** [comment]
hi @EvgenyOrekhov, jslint recently shipped with
- async/await,
- 100% regression-coverage,
- and lots of inlined, source-code-documentation (to make hacking/navigating its core-logic much easier).
