### ISSUE TITLE
JSLint should warn on \ in /\-/u

### ISSUE THREAD

**Issue by EvgenyOrekhov** [douglascrockford/JSLint#254]
Chrome and Firefox throw an error for `/\-/u`

![image](https://user-images.githubusercontent.com/8045060/65056110-fae31600-d978-11e9-89a0-25aa66cb65e7.png)

JSLint should not allow `\` before `-` in a regex if the `u` flag is used.

**Comment by douglascrockford** [comment]
Why does that happen?

**Comment by EvgenyOrekhov** [comment]
The ECMAScript standard is too hard to comprehend for me, but some articles on the internet say that the `u` flag for regexes acts as `"strict mode";` for JS. It's one of its features. It throws errors when you don't escape something that should be escaped, it throws errors when you escape something that should not be escaped, and it throws errors in some other cases.

**Comment by kaizhu256** [comment]
> Why does that happen?

found the reason @ https://github.com/tc39/proposal-regexp-unicode-property-escapes#what-about-backwards-compatibility

> What about backwards compatibility?
> In regular expressions without the u flag, the pattern \p is an (unnecessary) escape sequence for p. Patterns of the form \p{Letter} might already be present in existing regular expressions without the u flag, and therefore we cannot assign new meaning to such patterns without breaking backwards compatibility.
> 
> For this reason, ECMAScript 2015 made unnecessary escape sequences like \p and \P throw an exception when the u flag is set. This enables us to change the meaning of \p{…} and \P{…} in regular expressions with the u flag without breaking backwards compatibility.

**Comment by EvgenyOrekhov** [comment]
I don't care anymore.
