### ISSUE TITLE
Additional spaces in curried function calls

### ISSUE THREAD

**Issue by jlrwi** [douglascrockford/JSLint#259]
When using curried functions, this style:
```javascript
my_func(x)(y)(z)
```
is cluttered by the parentheses, which resulted in the [Sanctuary](https://github.com/sanctuary-js/sanctuary#-currying) library adopting this style:
```javascript
my_func (x) (y) (z)
```
I request that this spacing be permitted in the whitespace rules for JSLint as it improves readability.

**Comment by douglascrockford** [comment]
That is not more readable.
