### ISSUE TITLE
Why require space between `import` and `(`?

### ISSUE THREAD

**Issue by EvgenyOrekhov** [douglascrockford/JSLint#261]
![Screenshot_20200317_225332](https://user-images.githubusercontent.com/8045060/76896040-35832800-68a2-11ea-8872-794b6d20a812.jpg)

**Comment by douglascrockford** [comment]
import is not a function. import is a statement.

**Comment by EvgenyOrekhov** [comment]
I don't see the word "statement" anywhere in the proposal: https://tc39.es/proposal-dynamic-import/. The proposal refers to it as `import call` and `import() expression`, and there is no space between `import` and `(`.

**Comment by douglascrockford** [comment]
Is it allowed in expression position?

**Comment by EvgenyOrekhov** [comment]
Yes. It produces a value (a promise), so one can assign it to a variable, pass it around, etc.

**Comment by douglascrockford** [comment]
Thanks.
