### ISSUE TITLE
Why doesn't JSLint allow variables in `import()`?

### ISSUE THREAD

**Issue by EvgenyOrekhov** [douglascrockford/JSLint#262]
```js
/*jslint browser */

const urlToModuleMap = {
    "/": "./home.js",
    "/about": "./about.js"
};

const currentPageModule = urlToModuleMap[location.pathname] || "./notFound.js";

import(currentPageModule).then(renderPage);
```

> Expected a string and instead saw 'currentPageModule'.
> `import(currentPageModule).then(renderPage);`

**Comment by douglascrockford** [comment]
One of the good parts of ES6 modules was that the module identifiers were constants, making it possible to statically determine the dependencies. I don't want to give that up.
