### ISSUE TITLE
Unexpected ': foo' if local variable has same name as object property.

### ISSUE THREAD

**Issue by dvhx** [douglascrockford/JSLint#273]
var a = [];
var fo = 1;
var foo = 2;
a.push({foo: fo});   // this is ok
a.push({foo: foo});  // this is Unexpected ': foo'.

**Comment by EvgenyOrekhov** [comment]
Should be `a.push({foo})`. See https://ui.dev/shorthand-properties/.

**Comment by dvhx** [comment]
Can you please then change warning "Use shorthand property" instead of "Unexpected foo"? I honestly thought linter is confusing local variable with object property.

**Comment by douglascrockford** [comment]
The warning was not "Unexpected foo". It was "Unexpected ': foo'."
