### ISSUE TITLE
using node:true continues not accepting __dirname

### ISSUE THREAD

**Issue by zanona** [douglascrockford/JSLint#39]
Using `node: true` continues not accepting `__dirname` while `Disallow dangling _ in identifiers` is checked    

``` javascript
/*jslint devel: true, node: true, nomen: true, maxerr: 50, indent: 4 */

console.log(__dirname);
```

> Error: 
> Problem at line 1 character 13: Unexpected dangling '_' in '__dirname'.
> console.log(__dirname);

_source_: [jslint.com](http://jslint.com) live editor

**Comment by mk-pmb** [comment]
As far as I can tell from the docs and some testing, `__dirname` is a less reliable shorthand for `require("path").dirname(module.filename);`. I prefer the latter because it will always give an absolute path, so paths based on that won't crumble when your process changes its working directory.
