### ISSUE TITLE
Feature request related to /*global */

### ISSUE THREAD

**Issue by mythril** [douglascrockford/JSLint#96]
I've noticed that over time my /_global blah_/ line accrues cruft, I was hoping to find an option to warn me when I have unused globals declared. 

I mean to say that often I refactor code into two or more independent bits, one or more of the independent bits no longer has the same global dependency as the ancestral code. 

Often out of haste, ignorance, or accident, I allow the global line to keep the cruft of the ancestral code, which later on makes me think that this code somehow uses the global in question (often as a library).

**Comment by Kolyunya** [comment]
@douglascrockford I'm voting up to perform validation of unused globals. Even if there are very few of them (e.g. one) they still may be unused and a code quality tool must check this.

> If you have more than you can easily manage, then you have way too many.
What do you mean by `easily manage`? Easily perform a manual check of each of the 1000+ JS files in my project after each commit? Why do we need automation tools then if we need to perform manual checks after them?
